const puppeteer = require('puppeteer');
const path = require('path');
const wait = ms => new Promise(r => setTimeout(r, ms));
(async () => {
  const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox'] });
  const page = await browser.newPage();
  await page.setViewport({ width: 390, height: 844, deviceScaleFactor: 2 });
  page.on('console', msg => console.log('CONSOLE', msg.type(), msg.text()));
  page.on('pageerror', err => console.log('PAGEERROR', err.message));
  const filePath = 'file://' + path.resolve(__dirname, 'index.html') + '?nocache=' + Date.now();
  await page.goto(filePath, { waitUntil: 'networkidle0' });
  await page.waitForFunction(() => document.getElementById('buildChip').textContent !== '—', { timeout: 10000 });
  await page.evaluate(() => { localStorage.removeItem('spoons.me'); localStorage.removeItem('spoons.high.arcade'); });
  await page.click('#btnArcade');
  await page.waitForFunction(() => document.getElementById('orderPanel').classList.contains('open'), { timeout: 10000 });
  await wait(500);
  const handle = 'TEST' + Math.floor(Math.random()*100000);
  const res = await page.evaluate(h => {
    const n = document.getElementById('signupName');
    const p = document.getElementById('signupPub');
    console.log('before set', n.value, p.value);
    n.value = h;
    p.value = 'TEST LOCAL';
    console.log('after set', n.value, p.value);
    doSignup();
    return { signedIn: document.getElementById('signedInAs').style.display };
  }, handle);
  console.log('res', res);
  await wait(1000);
  const post = await page.evaluate(() => ({ signedIn: document.getElementById('signedInAs').style.display, tableHidden: document.getElementById('screen-table').classList.contains('hidden'), phase: window.__game.phase, pendingMode: window.__game.pendingMode }));
  console.log('post', post);
  await browser.close();
})();
